//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IDataService")]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Hello", ReplyAction="http://tempuri.org/IDataService/HelloResponse")]
        void Hello();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/CheckUser", ReplyAction="http://tempuri.org/IDataService/CheckUserResponse")]
        string CheckUser(string UserName, string Pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetJson", ReplyAction="http://tempuri.org/IDataService/GetJsonResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string GetJson(string Bll, string Exc, object[] par);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetImage", ReplyAction="http://tempuri.org/IDataService/GetImageResponse")]
        string GetImage(string Imagefilename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetBoxInfo", ReplyAction="http://tempuri.org/IDataService/GetBoxInfoResponse")]
        string GetBoxInfo(string TicketID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetTicketInfo", ReplyAction="http://tempuri.org/IDataService/GetTicketInfoResponse")]
        string GetTicketInfo(string TicketID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/EmpAddWork", ReplyAction="http://tempuri.org/IDataService/EmpAddWorkResponse")]
        string EmpAddWork(string TicketInfoID, string EmpID, string TicketTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Ordering", ReplyAction="http://tempuri.org/IDataService/OrderingResponse")]
        string Ordering(string EID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/EmpAtt", ReplyAction="http://tempuri.org/IDataService/EmpAttResponse")]
        string EmpAtt(string EID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : WebApplication1.ServiceReference2.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReference2.IDataService>, WebApplication1.ServiceReference2.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Hello() {
            base.Channel.Hello();
        }
        
        public string CheckUser(string UserName, string Pass) {
            return base.Channel.CheckUser(UserName, Pass);
        }
        
        public string GetJson(string Bll, string Exc, object[] par) {
            return base.Channel.GetJson(Bll, Exc, par);
        }
        
        public string GetImage(string Imagefilename) {
            return base.Channel.GetImage(Imagefilename);
        }
        
        public string GetBoxInfo(string TicketID) {
            return base.Channel.GetBoxInfo(TicketID);
        }
        
        public string GetTicketInfo(string TicketID) {
            return base.Channel.GetTicketInfo(TicketID);
        }
        
        public string EmpAddWork(string TicketInfoID, string EmpID, string TicketTime) {
            return base.Channel.EmpAddWork(TicketInfoID, EmpID, TicketTime);
        }
        
        public string Ordering(string EID) {
            return base.Channel.Ordering(EID);
        }
        
        public string EmpAtt(string EID) {
            return base.Channel.EmpAtt(EID);
        }
    }
}
